---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prod-api-deployment
  labels:
    username: petenick
    env: perseverance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-prod-api
  template:
    metadata:
      labels:
        username: petenick
        env: perseverance
        app: app-prod-api
    spec:
      containers:
      - name: app-prod-api
        image: petenick/perseverance-tracker-api:VER
        imagePullPolicy: Always
        command: ['sh', '-c', 'python3 /code/app.py']
        env:
        - name: FLASK_APP
          value: "/code/app.py"
        ports:
        - name: http
          containerPort: 5000
