---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prod-wrk-deployment
  labels:
    app: app-prod-wrk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-prod-wrk
  template:
    metadata:
      labels:
        app: app-prod-wrk
    spec:
      containers:
        - name: app-prod-wrk
          imagePullPolicy: Always
          image: petenick/perseverance-tracker-wrk:VER
          command: ['python', '-u', 'main.py']
          env:
          - <...>
          ports:
          - <...>
