---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-prod-pvc
  labels:
    username: petenick
    env: perseverance
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
