---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prod-db-deployment
  labels:
    username: petenick
    env: perseverance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-prod-db
  template:
    metadata:
      labels:
        username: petenick
        env: perseverance
        app: app-prod-db
    spec:
      containers:
      - name: petenick-db-container
        image: redis:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 6379
        volumeMounts:
        - name: app-prod-pvc
          mountPath: "/data"
      volumes:
      - name: app-prod-pvc
        persistentVolumeClaim:
          claimName: app-prod-pvc
