---
apiVersion: v1
kind: Service
metadata:
  name: app-prod-db-service
  labels:
    username: petenick
    env: perseverance
spec:
  type: ClusterIP
  selector:
    username: petenick
    env: perseverance
    app: app-prod-db
  ports:
  - name: app-prod-db-service
    port: 5015
    targetPort: 6379
