---
apiVersion: v1
kind: Service
metadata:
  name: ptracker-petenick-broadcast-service
spec:
  type: NodePort
  selector:
    app: petenick-flask
  ports:
  - name: petenick-flask
    port: 5000
    targetPort: 5000
    nodePort: 30042