---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptracker-petenick-flask
  labels:
    username: petenick
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petenick-flask
  template:
    metadata:
      labels:
        username: petenick
        env: prod
        app: petenick-flask
    spec:
      containers:
      - name: petenick-flask-container
        imagePullPolicy: Always
        image: petelealiieej/perseverance-tracker-api:0.1
        env:
        - name: FLASK_APP
          value: "app.py"
        ports:
        - name: http
          containerPort: 5000
