---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptracker-petenick-wrk
  labels:
    app: petenick-wrk
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petenick-wrk
  template:
    metadata:
      labels:
        username: petenick
        env: prod
        app: petenick-wrk
    spec:
      containers:
        - name: petenick-wrk
          imagePullPolicy: Always
          image: petelealiieej/perseverance-tracker-wrk:0.1
