# Image: jstubbs/animals-service
FROM python:3.9

ADD ./requirements_wrk.txt /requirements.txt
RUN pip install -r requirements.txt
COPY ./src /app
WORKDIR /app

ENTRYPOINT ["python"]
CMD ["-u", "worker.py"]