---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ptracker-petenick-data-test
  labels:
    username: petenick
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
