---
apiVersion: v1
kind: Service
metadata:
  name: ptracker-petenick-redis-service
  labels:
    username: petenick
    env: test
spec:
  type: ClusterIP
  selector:
    app: petenick-redis
  ports:
  - name: petenick-redis
    port: 6379
    targetPort: 6379
